# Generated by Django 4.2.7 on 2024-05-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stock_symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
